services:
  # This is the service for your Python application
  api:
    # Build the image from the Dockerfile in the current directory
    build: .
    
    image: goodbooksunisoft/po-ai-agent:latest
    # Give the running container a consistent name
    container_name: po-agent
    
    # Make the container restart automatically if it stops
    restart: always
    
    # Map port 8004 on your machine to port 8004 in the container
    ports:
      - "8004:8004"
      
    # Load environment variables from the .env file
    env_file:
      - .env